package APs;

import oracle.jbo.common.PropertiesBundleDef;
import oracle.jbo.server.ApplicationModuleDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Oct 05 13:47:31 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleDefImpl extends ApplicationModuleDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleDefImpl() {
    }

    @Override
    protected void finishedLoading() {
        super.finishedLoading();
        PropertiesBundleDef pbd = new PropertiesBundleDef(this);
        pbd.setPropertiesFile("model.ModelBundle");
        setResourceBundleDef(pbd);
    }
}

