package model;

import model.common.AppModule;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 14 21:04:37 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for EmployeesView1.
     * @return EmployeesView1
     */
    public EmployeesViewImpl getEmployeesView1() {
        return (EmployeesViewImpl) findViewObject("EmployeesView1");
    }
    
    
    public int add(int x, int y){
        return(x+y);
    }
    
    public String runQry(){
        ViewObjectImpl vo = this.getEmployeesView1();
        vo.executeQuery();
        RowSetIterator rs = vo.createRowSetIterator(null);
        String fname="";
        while(rs.hasNext()){
            Row r = rs.next();
            fname = fname +"," + r.getAttribute("FirstName");
        }
        return fname;
    }
    
    
    public String runQueryWithParams(int d){
        ViewObjectImpl vo = this.getEmployeesView1();
        vo.setNamedWhereClauseParam("bDeptId", d);
        vo.executeQuery();
        RowSetIterator rs = vo.createRowSetIterator(null);
        String fname="";
        while(rs.hasNext()){
            Row r = rs.next();
            fname = fname +"," + r.getAttribute("FirstName");
        }
        return fname;
    }
    
    

    /**
     * Container's getter for JobsView1.
     * @return JobsView1
     */
    public ViewObjectImpl getJobsView1() {
        return (ViewObjectImpl) findViewObject("JobsView1");
    }

    /**
     * Container's getter for DepartmentsView1.
     * @return DepartmentsView1
     */
    public ViewObjectImpl getDepartmentsView1() {
        return (ViewObjectImpl) findViewObject("DepartmentsView1");
    }
}

