package model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 21 15:17:55 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class CountryNewEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public CountryNewEOCollImpl() {
    }
}

