package model;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 24 15:38:41 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DVTPieChartVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DVTPieChartVOImpl() {
    }
}

