package model;

import oracle.jbo.domain.Number;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Sep 14 21:04:00 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmployeesViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public EmployeesViewImpl() {
    }


    /**
     * Returns the variable value for bDeptId.
     * @return variable value for bDeptId
     */
    public Integer getbDeptId() {
        return (Integer) ensureVariableManager().getVariableValue("bDeptId");
    }

    /**
     * Sets <code>value</code> for variable bDeptId.
     * @param value value to bind as bDeptId
     */
    public void setbDeptId(Integer value) {
        ensureVariableManager().setVariableValue("bDeptId", value);
    }
}

