package model;

import oracle.jbo.server.EntityCache;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 24 14:21:34 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesEOCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public SalesEOCollImpl() {
    }
}

