package model;

import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Sep 24 14:21:33 IST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class SalesEODefImpl extends EntityDefImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public SalesEODefImpl() {
    }
}

