package model.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Sep 15 11:11:37 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    int add(int x, int y);

    String runQry();

    String runQueryWithParams(int d);
}

