package APs.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 06 11:44:22 IST 2020
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void foo();
}

